### ISSUE TITLE
Single sign out dosen't work with redis_store

### ISSUE THREAD

**Issue by tianlu1677** [nbudin/devise_cas_authenticatable#106] opened 2015-08-11 14:41 UTC
### I use redis to store my session, but i can't logout other system.

this is version
```
ruby 2.2.1
rails 4.2.1
devise_cas_authenticatable (1.5.0)
      devise (>= 1.2.0)
      rubycas-client (>= 2.2.1)
```

```
my session_store
  Rails.application.config.session_store :redis_store, :servers => { :host => Settings.redis_server_host, :port => Settings.redis_server_port, :db => 0, :namespace => 'sessions', :expire_after => 10.minutes }
 
```
and  routes
```
devise_for :users, :controllers => { :cas_sessions => "users/cas_sessions", :registrations => "users/registrations", :confirmations => "users/confirmations", :passwords => "users/passwords", :emails=>"users/emails" }
  devise_scope :user do
   
    get "users/sign_in", to: "users/cas_sessions#new"
    delete "users/sign_out", to: "users/cas_sessions#destroy"
  end

```
this is link url

```
users_sign_out_path	DELETE	/users/sign_out(.:format)	users/cas_sessions#destroy
```

this is my cas_session_controller, I just copy from gem
```
class Users::CasSessionsController < Devise::CasSessionsController
  include DeviseCasAuthenticatable::SingleSignOut::DestroySession

  unless Rails.version =~/^4/
    unloadable
  end

  skip_before_filter :verify_authenticity_token, :only => [:single_sign_out]

  def new
    redirect_to(cas_login_url)
  end

  def service
    redirect_to after_sign_in_path_for(warden.authenticate!(:scope => resource_name))
  end

  def unregistered
  end

  def destroy
    # if :cas_create_user is false a CAS session might be open but not signed_in
    # in such case we destroy the session here
    if signed_in?(resource_name)
      sign_out(resource_name)
      # single_sign_out
    else
      reset_session
    end

    redirect_to(cas_logout_url)
  end

  def single_sign_out
    if ::Devise.cas_enable_single_sign_out
      session_index = read_session_index
      if session_index
        logger.debug "Intercepted single-sign-out request for CAS session #{session_index}."
        session_id = ::DeviseCasAuthenticatable::SingleSignOut::Strategies.current_strategy.find_session_id_by_index(session_index)
        if session_id
          logger.debug "Found Session ID #{session_id} with index key #{session_index}"
          destroy_cas_session(session_index, session_id)
        end
      else
        logger.warn "Ignoring CAS single-sign-out request as no session index could be parsed from the parameters."
      end
    else
      logger.warn "Ignoring CAS single-sign-out request as feature is not currently enabled."
    end

    render :nothing => true
  end

  private

  def read_session_index
    if request.headers['CONTENT_TYPE'] =~ %r{^multipart/}
      false
    elsif request.post? && params['logoutRequest'] =~ %r{^<samlp:LogoutRequest.*?<samlp:SessionIndex>(.*)</samlp:SessionIndex>}m
      $~[1]
    else
      false
    end
  end

  def destroy_cas_session(session_index, session_id)
    if destroy_session_by_id(session_id)
      logger.debug "Destroyed session #{session_id} corresponding to service ticket #{session_index}."
    end
    ::DeviseCasAuthenticatable::SingleSignOut::Strategies.current_strategy.delete_session_index(session_index)
  end

  def cas_login_url
    ::Devise.cas_client.add_service_to_login_url(::Devise.cas_service_url(request.url, devise_mapping))
  end
  helper_method :cas_login_url

  def request_url
    return @request_url if @request_url
    @request_url = request.protocol.dup
    @request_url << request.host
    @request_url << ":#{request.port.to_s}" unless request.port == 80
    @request_url
  end

  def cas_destination_url
    return unless ::Devise.cas_logout_url_param == 'destination'
    if !::Devise.cas_destination_url.blank?
      url = Devise.cas_destination_url
    else
      url = request_url.dup
      url << after_sign_out_path_for(resource_name)
    end
  end

  def cas_follow_url
    return unless ::Devise.cas_logout_url_param == 'follow'
    if !::Devise.cas_follow_url.blank?
      url = Devise.cas_follow_url
    else
      url = request_url.dup
      url << after_sign_out_path_for(resource_name)
    end
  end

  def cas_service_url
    ::Devise.cas_service_url(request_url.dup, devise_mapping)
  end

  def cas_logout_url
    begin
      ::Devise.cas_client.logout_url(cas_destination_url, cas_follow_url, cas_service_url)
    rescue ArgumentError
      # Older rubycas-clients don't accept a service_url
      ::Devise.cas_client.logout_url(cas_destination_url, cas_follow_url)
    end
  end
end

```

so when i click the view
```
    <h1><%= link_to "destroy", destroy_user_session_path, method: :delete%></h1>

```

It just get sign_out and don't run single_sign_out method
```
Remote Address:127.0.0.1:3001
Request URL:http://hotfix-fudan.kaikeba.dev:3001/users/sign_out
Request Method:GET
Status Code:302 Found

-----------------------------
Remote Address:192.168.30.39:443
Request URL:https://hotfix-passport.kaikeba.cn/logout?service=http%3A%2F%2Fhotfix-fudan.kaikeba.dev%3A3001%2Fusers%2Fservice
Request Method:GET
Status Code:200 OK

```

This is the log

```
Started GET "/users/sign_out" for 127.0.0.1 at 2015-08-11 22:36:42 +0800
Processing by Users::CasSessionsController#destroy as HTML
  User Load (3.6ms)  SELECT  "users".* FROM "users" WHERE "users"."status" = $1 AND "users"."id" = $2  ORDER BY "users"."id" ASC LIMIT 1  [["status", "active"], ["id", 541513]]
  School Load (3.3ms)  SELECT  "schools".* FROM "schools" WHERE "schools"."status" = 'online' AND "schools"."shortname" = $1  ORDER BY  schools.position asc  LIMIT 1  [["shortname", "hotfix-fudan"]]
  Tenant Load (3.3ms)  SELECT  "tenants".* FROM "tenants" WHERE "tenants"."id" = $1 LIMIT 1  [["id", 223]]
  School Exists (2.7ms)  SELECT  1 AS one FROM "schools" WHERE "schools"."status" = 'online' AND "schools"."shortname" = $1 LIMIT 1  [["shortname", "hotfix-fudan"]]
   (2.3ms)  BEGIN
   (2.7ms)  COMMIT
Redirected to https://hotfix-passport.kaikeba.cn/logout?service=http%3A%2F%2Fhotfix-fudan.kaikeba.dev%3A3001%2Fusers%2Fservice
Completed 302 Found in 161ms (ActiveRecord: 17.9ms)
```

I try many methods and I don't know where I did not get. 

thanks.

**Comment by nbudin** [comment] 2015-08-11 15:19
I'm not sure I completely follow what is going on in your code.  In a single sign-out server, there should be two applications involved: a CAS client, and a CAS server.  I'm guessing what we are looking at is the CAS client, based on the fact that you've included `devise_cas_authenticatable` in it, but please correct me if I'm wrong.

The app responsible for making the call to `single_sign_out` is the CAS server.  Since that call is never happening at all, I would guess that the server is not correctly configured to make single sign-out calls to your client app.  Which CAS server are you using?

As an aside, it also seems like you've copy/pasted the code for `Devise::CasSessionsController` from the gem into your app.  It may be better to simply inherit from that class in your code and override just the parts you've changed, which would make it easier for you and others to debug.

**Comment by tianlu1677** [comment] 2015-08-11 16:37
You are right. I just showed  CAS-client. Then I watch CAS-server and set config.yml  `enable_single_sign_out: true`.

I see code in `server.rb`
```
CASServer::Model::TicketGrantingTicket.transaction do
          $LOG.debug("Deleting Service/Proxy Tickets for '#{tgt}' for user '#{tgt.username}'")
          tgt.granted_service_tickets.each do |st|
            send_logout_notification_for_service_ticket(st) if config[:enable_single_sign_out]
            # TODO: Maybe we should do some special handling if send_logout_notification_for_service_ticket fails?
            #       (the above method returns false if the POST results in a non-200 HTTP response).
            $LOG.debug "Deleting #{st.class.name.demodulize} #{st.ticket.inspect} for service #{st.service}."
            st.destroy
          end

```
 then I watch log and It failed to send notify to client. 
```
Deleting Service/Proxy Tickets for 'TGC-1439310696r3p1o-sbYgOjeOWZBTV' for user 'yguo@kaikeba.com'
  CASServer::Model::ServiceTicket Load (207.3ms)  SELECT "casserver_st".* FROM "casserver_st" WHERE "casserver_st"."type" IN ('CASServer::Model::ServiceTicket') AND "casserver_st"."granted_by_tgt_id" = 746524
Failed to send logout notification to service "http://hotfix-buaa.kaikeba.cn/users/service" due to getaddrinfo: Temporary failure in name resolution
Deleting ServiceTicket "ST-1439310696rGAOFHTc-1k9dZCjtQU" for service http://hotfix-buaa.kaikeba.cn/users/service.
  SQL (2.5ms)  DELETE FROM "casserver_st" WHERE "casserver_st"."type" IN ('CASServer::Model::ServiceTicket') AND "casserver_st"."id" = $1  [["id", 2303730]]
```
This is CORS or other reason？

**Comment by nbudin** [comment] 2015-08-11 19:27
Well, as your server says: `getaddrinfo: Temporary failure in name resolution`.  This probably means that for whatever reason, DNS resolution of `hotfix-buaa.kaikeba.cn` is failing on your server.

**Comment by nbudin** [comment] 2015-08-11 19:27
This is clearly not a bug in `devise_cas_authenticatable`, so I am closing this ticket.

**Closed by nbudin** 2015-08-11 19:27 UTC
